/**
 * Video testimonials.
 *
 * Clips are generated on fal.ai by scripts/generate-videos.mjs (see README) and live in
 * public/videos/. A card without `src` renders an animated placeholder with `captions`
 * instead, so the page still works if a clip is removed.
 */
export type VideoTestimonial = {
  id: string;
  name: string;
  title: string;
  duration: string;
  captions: string[];
  hue: number;
  src?: string;
  poster?: string;
  /** Vertical clips (season 2) sit in their own swipeable row and open full-height. */
  aspect?: "9:16";
};

/** The infomercial clip for the "Watch the ad" modal. Undefined = flashing text fallback. */
export const adVideo: { src: string; poster: string } | undefined = {
  src: "/videos/ad.mp4",
  poster: "/videos/ad.jpg",
};

export const videos: VideoTestimonial[] = [
  {
    id: "linda",
    name: "Linda, 47",
    title: "“I ordered that shit at 2am”",
    duration: "0:08",
    hue: 12,
    src: "/videos/linda.mp4",
    poster: "/videos/linda.jpg",
    captions: [
      "It was 2am.",
      "I couldn't sleep.",
      "So I ordered that shit.",
      "I still can't sleep.",
      "But now it's next to me.",
    ],
  },
  {
    id: "marcus",
    name: "Marcus, DevOps",
    title: "“Production was down”",
    duration: "0:08",
    hue: 210,
    src: "/videos/marcus.mp4",
    poster: "/videos/marcus.jpg",
    captions: [
      "The pager went off.",
      "Everything was on fire.",
      "I ordered that shit.",
      "The fire is still there.",
      "Morale? Through the roof.",
    ],
  },
  {
    id: "gary",
    name: "Gary, 61",
    title: "“It arrived on time”",
    duration: "0:08",
    hue: 140,
    src: "/videos/gary.mp4",
    poster: "/videos/gary.jpg",
    captions: [
      "She said it's me or the shit.",
      "The shit had tracking.",
      "She did not.",
      "Three to five business days.",
      "Exactly as promised.",
    ],
  },
  {
    id: "ceo",
    name: "Our CEO",
    title: "“A message from leadership”",
    duration: "0:08",
    hue: 45,
    src: "/videos/ceo.mp4",
    poster: "/videos/ceo.jpg",
    captions: [
      "When I founded this company,",
      "I had one question:",
      "what is that shit?",
      "I still don't know.",
      "But we've sold millions.",
    ],
  },
  // Season 2: vertical, native for phones. Generated by scripts/generate-videos.mjs
  // (the 9:16 characters in scripts/video-characters.mjs).
  {
    id: "diane",
    name: "Diane, 58",
    title: "“Now I understand him”",
    duration: "0:08",
    hue: 30,
    aspect: "9:16",
    src: "/videos/diane.mp4",
    poster: "/videos/diane.jpg",
    captions: ["Gary chose the shit.", "So I ordered some shit too.", "Now I understand him.", "We're still not getting back together."],
  },
  {
    id: "walter",
    name: "Walter, 83",
    title: "“You don't wait for a sale”",
    duration: "0:08",
    hue: 90,
    aspect: "9:16",
    src: "/videos/walter.mp4",
    poster: "/videos/walter.jpg",
    captions: ["At my age,", "you don't wait for a sale.", "You order that shit."],
  },
  {
    id: "priya",
    name: "Priya, 29",
    title: "“Out for delivery”",
    duration: "0:08",
    hue: 320,
    aspect: "9:16",
    src: "/videos/priya.mp4",
    poster: "/videos/priya.jpg",
    captions: ["Refreshed the tracking page forty times today.", "Out for delivery.", "Best three words in English."],
  },
  {
    id: "therapist",
    name: "Dr. Helen, 55",
    title: "“I'm out of a job”",
    duration: "0:07",
    hue: 280,
    aspect: "9:16",
    src: "/videos/therapist.mp4",
    poster: "/videos/therapist.jpg",
    captions: ["Twenty years as a therapist.", "My best patient just ordered that shit.", "Cured.", "I'm out of a job."],
  },
  {
    id: "donna",
    name: "Donna, 64",
    title: "“Nineteen Black Fridays”",
    duration: "0:08",
    hue: 0,
    aspect: "9:16",
    src: "/videos/donna.mp4",
    poster: "/videos/donna.jpg",
    captions: ["Nineteen Black Fridays.", "Two broken wrists.", "This year I ordered that shit from bed.", "Like a professional."],
  },
  {
    id: "luis",
    name: "Luis, delivery",
    title: "“Happy crying. Mostly.”",
    duration: "0:08",
    hue: 200,
    aspect: "9:16",
    src: "/videos/luis.mp4",
    poster: "/videos/luis.jpg",
    captions: ["I deliver that shit.", "People cry when they see me.", "Happy crying.", "Mostly."],
  },
  {
    id: "kevin",
    name: "Kevin, support",
    title: "“Your problem is important to us”",
    duration: "0:08",
    hue: 160,
    aspect: "9:16",
    src: "/videos/kevin.mp4",
    poster: "/videos/kevin.jpg",
    captions: ["Thank you for calling Order That Shit.", "Your problem is very important to us.", "Have you tried ordering more shit?"],
  },
];

/**
 * The commercials: multi-shot parodies of real ad genres, vertical, built by scripts/make-ads.mjs
 * from the spots in scripts/ads.mjs.
 */
export const commercials: VideoTestimonial[] = [
  {
    id: "ad-pharma",
    name: "Ask your doctor",
    title: "“Side effects may include closure”",
    duration: "0:32",
    hue: 200,
    aspect: "9:16",
    src: "/videos/ad-pharma.mp4",
    poster: "/videos/ad-pharma.jpg",
    captions: [],
  },
  {
    id: "ad-better-way",
    name: "As seen on TV",
    title: "“There's got to be a better way!”",
    duration: "0:29",
    hue: 280,
    aspect: "9:16",
    src: "/videos/ad-better-way.mp4",
    poster: "/videos/ad-better-way.jpg",
    captions: [],
  },
  {
    id: "ad-fragrance",
    name: "SHIT, the fragrance",
    title: "“Eau de Having Ordered It”",
    duration: "0:14",
    hue: 0,
    aspect: "9:16",
    src: "/videos/ad-fragrance.mp4",
    poster: "/videos/ad-fragrance.jpg",
    captions: [],
  },
  {
    id: "ad-migration",
    name: "Black Friday",
    title: "“The Great Migration”",
    duration: "0:30",
    hue: 30,
    aspect: "9:16",
    src: "/videos/ad-migration.mp4",
    poster: "/videos/ad-migration.jpg",
    captions: [],
  },
];
